import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import NavBar from "../../components/NavBar";
import Footer from "../../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CrimeShield BD",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel="icon" href="/logo.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav>
          <NavBar />
        </nav>

        <div className="min-h-screen">{children}</div>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
